hugo:
  image: jermine/hugo
  command: >
   hugo server --bind=0.0.0.0
           --port=80
           --baseUrl=http://blog.easypi.info/
           --watch
  ports:
    - "80:80"
  volumes:
    - ./www:/www
  restart: always